### ISSUE TITLE
work with proctoring moodle

### ISSUE THREAD

**Issue by hafriz** [AhnafMuttaki/face_recognition_flask_api#1]
hi AhnafMuttaki,

may i know if this face_recognition works with moodle proctoring quiz modules? i have tried this flask API and manually download the webcam picture that captures by moodle proctoring. it seems cannot be processed and found, i have tried other tools for face recognition and the webcam picture seems cannot process / cannot detect the face. do you know any workaround to make it work? 

it is working with other image captured from other camera or another picture

thanks

**Comment by AhnafMuttaki** [comment]
sorry ... no it does not work with proctoring
